run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - bodyclose
    - sqlclosecheck

issues:
  exclude-dirs:
    - migrations
