// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/interfaces.go -destination=internal/service/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/ikukhar/refuel-backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), user)
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), email)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(id uint) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockUserRepository) Update(user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), user)
}

// MockActivityRepository is a mock of ActivityRepository interface.
type MockActivityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActivityRepositoryMockRecorder
	isgomock struct{}
}

// MockActivityRepositoryMockRecorder is the mock recorder for MockActivityRepository.
type MockActivityRepositoryMockRecorder struct {
	mock *MockActivityRepository
}

// NewMockActivityRepository creates a new mock instance.
func NewMockActivityRepository(ctrl *gomock.Controller) *MockActivityRepository {
	mock := &MockActivityRepository{ctrl: ctrl}
	mock.recorder = &MockActivityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityRepository) EXPECT() *MockActivityRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockActivityRepository) Create(activity *model.Activity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockActivityRepositoryMockRecorder) Create(activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActivityRepository)(nil).Create), activity)
}

// FindBySourceID mocks base method.
func (m *MockActivityRepository) FindBySourceID(sourceID string) (*model.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySourceID", sourceID)
	ret0, _ := ret[0].(*model.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySourceID indicates an expected call of FindBySourceID.
func (mr *MockActivityRepositoryMockRecorder) FindBySourceID(sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySourceID", reflect.TypeOf((*MockActivityRepository)(nil).FindBySourceID), sourceID)
}

// FindByUserID mocks base method.
func (m *MockActivityRepository) FindByUserID(userID uint, from, to *time.Time, limit, offset int) ([]model.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", userID, from, to, limit, offset)
	ret0, _ := ret[0].([]model.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockActivityRepositoryMockRecorder) FindByUserID(userID, from, to, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockActivityRepository)(nil).FindByUserID), userID, from, to, limit, offset)
}

// MockDailyNutritionRepository is a mock of DailyNutritionRepository interface.
type MockDailyNutritionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDailyNutritionRepositoryMockRecorder
	isgomock struct{}
}

// MockDailyNutritionRepositoryMockRecorder is the mock recorder for MockDailyNutritionRepository.
type MockDailyNutritionRepositoryMockRecorder struct {
	mock *MockDailyNutritionRepository
}

// NewMockDailyNutritionRepository creates a new mock instance.
func NewMockDailyNutritionRepository(ctrl *gomock.Controller) *MockDailyNutritionRepository {
	mock := &MockDailyNutritionRepository{ctrl: ctrl}
	mock.recorder = &MockDailyNutritionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDailyNutritionRepository) EXPECT() *MockDailyNutritionRepositoryMockRecorder {
	return m.recorder
}

// FindByUserAndDate mocks base method.
func (m *MockDailyNutritionRepository) FindByUserAndDate(ctx context.Context, userID uint, date time.Time) (*model.DailyNutrition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAndDate", ctx, userID, date)
	ret0, _ := ret[0].(*model.DailyNutrition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserAndDate indicates an expected call of FindByUserAndDate.
func (mr *MockDailyNutritionRepositoryMockRecorder) FindByUserAndDate(ctx, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAndDate", reflect.TypeOf((*MockDailyNutritionRepository)(nil).FindByUserAndDate), ctx, userID, date)
}

// Upsert mocks base method.
func (m *MockDailyNutritionRepository) Upsert(ctx context.Context, n *model.DailyNutrition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDailyNutritionRepositoryMockRecorder) Upsert(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDailyNutritionRepository)(nil).Upsert), ctx, n)
}

// MockRecipeRepository is a mock of RecipeRepository interface.
type MockRecipeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecipeRepositoryMockRecorder
	isgomock struct{}
}

// MockRecipeRepositoryMockRecorder is the mock recorder for MockRecipeRepository.
type MockRecipeRepositoryMockRecorder struct {
	mock *MockRecipeRepository
}

// NewMockRecipeRepository creates a new mock instance.
func NewMockRecipeRepository(ctrl *gomock.Controller) *MockRecipeRepository {
	mock := &MockRecipeRepository{ctrl: ctrl}
	mock.recorder = &MockRecipeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipeRepository) EXPECT() *MockRecipeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecipeRepository) Create(recipe *model.Recipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", recipe)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRecipeRepositoryMockRecorder) Create(recipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecipeRepository)(nil).Create), recipe)
}

// Delete mocks base method.
func (m *MockRecipeRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecipeRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecipeRepository)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockRecipeRepository) FindAll() ([]model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRecipeRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRecipeRepository)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockRecipeRepository) FindByID(id uint) (*model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRecipeRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRecipeRepository)(nil).FindByID), id)
}

// FindByMealType mocks base method.
func (m *MockRecipeRepository) FindByMealType(mealType string) ([]model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByMealType", mealType)
	ret0, _ := ret[0].([]model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByMealType indicates an expected call of FindByMealType.
func (mr *MockRecipeRepositoryMockRecorder) FindByMealType(mealType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByMealType", reflect.TypeOf((*MockRecipeRepository)(nil).FindByMealType), mealType)
}

// FindByMealTypeExcludeIDs mocks base method.
func (m *MockRecipeRepository) FindByMealTypeExcludeIDs(mealType string, excludeIDs []uint) ([]model.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByMealTypeExcludeIDs", mealType, excludeIDs)
	ret0, _ := ret[0].([]model.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByMealTypeExcludeIDs indicates an expected call of FindByMealTypeExcludeIDs.
func (mr *MockRecipeRepositoryMockRecorder) FindByMealTypeExcludeIDs(mealType, excludeIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByMealTypeExcludeIDs", reflect.TypeOf((*MockRecipeRepository)(nil).FindByMealTypeExcludeIDs), mealType, excludeIDs)
}

// Update mocks base method.
func (m *MockRecipeRepository) Update(recipe *model.Recipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", recipe)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRecipeRepositoryMockRecorder) Update(recipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecipeRepository)(nil).Update), recipe)
}

// MockMealPeriodRepository is a mock of MealPeriodRepository interface.
type MockMealPeriodRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMealPeriodRepositoryMockRecorder
	isgomock struct{}
}

// MockMealPeriodRepositoryMockRecorder is the mock recorder for MockMealPeriodRepository.
type MockMealPeriodRepositoryMockRecorder struct {
	mock *MockMealPeriodRepository
}

// NewMockMealPeriodRepository creates a new mock instance.
func NewMockMealPeriodRepository(ctrl *gomock.Controller) *MockMealPeriodRepository {
	mock := &MockMealPeriodRepository{ctrl: ctrl}
	mock.recorder = &MockMealPeriodRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMealPeriodRepository) EXPECT() *MockMealPeriodRepositoryMockRecorder {
	return m.recorder
}

// FindByUserID mocks base method.
func (m *MockMealPeriodRepository) FindByUserID(userID uint) ([]model.MealPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", userID)
	ret0, _ := ret[0].([]model.MealPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockMealPeriodRepositoryMockRecorder) FindByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockMealPeriodRepository)(nil).FindByUserID), userID)
}

// Create mocks base method.
func (m *MockMealPeriodRepository) Create(p *model.MealPeriod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMealPeriodRepositoryMockRecorder) Create(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMealPeriodRepository)(nil).Create), p)
}

// DeleteByUserID mocks base method.
func (m *MockMealPeriodRepository) DeleteByUserID(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockMealPeriodRepositoryMockRecorder) DeleteByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockMealPeriodRepository)(nil).DeleteByUserID), userID)
}

// Update mocks base method.
func (m *MockMealPeriodRepository) Update(p *model.MealPeriod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMealPeriodRepositoryMockRecorder) Update(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMealPeriodRepository)(nil).Update), p)
}

// Delete mocks base method.
func (m *MockMealPeriodRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMealPeriodRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMealPeriodRepository)(nil).Delete), id)
}
